---
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: verify-image-provenance
  namespace: default
spec:
  validationFailureAction: enforce
  webhookTimeoutSeconds: 30
  rules:
    - name: attest
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
            - "ghcr.io/thomasvitale/*"
          attestations:
            - predicateType: https://slsa.dev/provenance/v0.2
              attestors:
                - count: 1
                  entries:
                    - keyless:
                        subject: "https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@refs/tags/v*"
                        issuer: "https://token.actions.githubusercontent.com"
                        rekor:
                          url: https://rekor.sigstore.dev
              conditions:
                - all:
                    - key: "{{ regex_match('^https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@refs/tags/v[0-9].[0-9].[0-9]$','{{ builder.id}}') }}"
                      operator: Equals
                      value: true
